apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kafkascraper
spec:
  template:
    spec:
      containers:
        - image: ko://github.com/aslom/repdroduce-kafka-source/KafkaScraper
