---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    spec:
      containers:
        - image: ko://github.com/aslom/repdroduce-kafka-source/customizeEventDisplay
      env:
      - name: displayConcurrentConnections
        value: "true"
      - name: cloudevent
        value: "true"
      - name: forward
        value: "true"
      - name: delay
        value: "3"
      - name: print
        value: "true"
      - name: scraper
        value: "https://kafkascraper-k9.o7-111a9c298953d78649164b7e8394bcdc-0000.us-south.containers.appdomain.cloud"
