---
apiVersion: batch/v1
kind: Job
metadata:
  name: scenario1-kafkaproduce-job1
spec:
  template:
    spec:
      containers:
      - name: scenario1-kafkaproduce-job1
        image: ko://github.com/aslom/repdroduce-kafka-source/KafkaProducer
        imagePullPolicy: Always
        env:
        - name: BROKERS
          value: "my-cluster-kafka-bootstrap.kafka:9092"
        - name: TOPIC
          value: "topic30"
        - name: EVENTCT
          value: "1"
        resources:
          requests:
            cpu: "0.5"
            memory: "0.5G"
          limits:
            cpu: "1"
            memory: "8G"
      restartPolicy: Never
  backoffLimit: 2
