---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: topic50a
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 50
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
