---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-src50
spec:
  consumerGroup: kafka-src50b
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  topics:
  - topic50a
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
